[package]
name = "object-store"
version = "0.1.0"
edition = "2021"


[dependencies]
#obliviate-core = { workspace = true }
chacha20 = { workspace = true, features = ["std", "zeroize"] }
#fatfs = { git = "https://github.com/twizzler-operating-system/rust-fatfs.git", branch = "zphrs-rwproxy", version = "0.4.0", features = [
#    "std",
#    "log_level_info",
#    "lfn",
#    "alloc",
#], default-features = false }
rand = "0.8"
intervaltree = { workspace = true, features = ["serde"] }
tracing = { workspace = true }
lru = { workspace = true }
lwext4-rs = { workspace = true }
smallvec = { workspace = true }
bitflags = "*"
libc = { workspace = true }

[target.'cfg(target_os = "twizzler")'.dependencies]
twizzler-abi = { path = "../../../lib/twizzler-abi" }
twizzler = { path = "../../../lib/twizzler" }
naming-core = { path = "../../../lib/naming/naming-core" }
pager-dynamic = { path = "../../../lib/pager/pager-dynamic" }

[dev-dependencies]
tracing-subscriber = { workspace = true }
